/*
 * This header is generated by sopc2dts on Sun Mar 02 11:05:11 PST 2014
 * Sopc2dts is written by Walter Goossens <waltergoossens@home.nl>
 * in cooperation with the nios2 community <Nios2-dev@sopc.et.ntust.edu.tw>
 */
#ifndef CUSTOM_FPGA_H_
#define CUSTOM_FPGA_H_

/* generated from kernel.sopcinfo */

/* Dumping slaves of cpu.data_master*/

/* cpu.jtag_debug_module is a altera_nios2_qsys */
#define CONFIG_SYS_CLK_FREQ	25000000
#define CONFIG_SYS_DCACHE_SIZE	32768
#define CONFIG_SYS_DCACHELINE_SIZE	32
#define CONFIG_SYS_ICACHELINE_SIZE	32
#define CONFIG_SYS_EXCEPTION_ADDR	0xd0000020
#define CONFIG_SYS_ICACHE_SIZE	32768
#define CONFIG_SYS_RESET_ADDR	0xc0020000
#define IO_REGION_BASE	0xE0000000

/* sysid.control_slave is a altera_avalon_sysid_qsys */
#define CONFIG_SYS_SYSID_BASE	0xe0001800

/* epcs.epcs_control_port is a altera_avalon_epcs_flash_controller */
#define EPCS_BASE	0xe0000400
#define EPCS_IRQ	1

/* jtag_uart.avalon_jtag_slave is a altera_avalon_jtag_uart */
#define CONFIG_SYS_JTAG_UART_BASE	0xe0003000

/* led.s1 is a altera_avalon_pio */
#define LED_BASE	0xe0004000

/* sd_clk.s1 is a altera_avalon_pio */
#define SD_CLK_BASE	0xe0006000

/* sd_cmd.s1 is a altera_avalon_pio */
#define SD_CMD_BASE	0xe0006010

/* sd_dat.s1 is a altera_avalon_pio */
#define SD_DAT_BASE	0xe0006020

/* timer_0.s1 is a altera_avalon_timer */
#define CONFIG_SYS_TIMER_IRQ	2
#define CONFIG_SYS_TIMER_FREQ	25000000
#define CONFIG_SYS_TIMER_BASE	0xe0006040

/* onchip_dram.s1 is a altera_avalon_onchip_memory2 */
#define ONCHIP_DRAM_BASE	0xe0020000

/* usb_uart.s1 is a altera_avalon_uart */
#define CONFIG_SYS_UART_BAUD	115200
#define CONFIG_SYS_UART_BASE	0xe0007800
#define CONFIG_SYS_UART_FREQ	25000000

/* ddr3_if.avl is a altera_mem_if_ddr3_emif */
#define CONFIG_SYS_SDRAM_BASE	0xd0000000
#define CONFIG_SYS_SDRAM_SIZE	0x8000000

#endif	//CUSTOM_FPGA_H_
